language: node_js
node_js:
  - "10"
before_deploy:
  - npm run build
deploy:
  edge: true
  provider: npm
  email: "$EMAIL"
  api_key: "$API_KEY"
  skip_cleanup: true
  on:
    branch: master

branches:
  only:
    - master